### ISSUE TITLE
Go outside from inside private node 

### ISSUE THREAD

**Issue by ykhacha** [grycap/ipfloater#5]
Hello again, the floating public ip address works properly from outside i can access private node, but when i try to reach internet or pinging 8.8.8.8 from inside private node it doesn't work.

**Comment by dealfonso** [comment]
hi, that is not an issue from ipfloater. The access to the network must be provided by means of nat or other mechanisms. A VM will not have knowledge about the existence of the public IP address. The traffic from the public IP address is redirected to the private IP address.

**Comment by ykhacha** [comment]
Hi, i'm sorry i'm not very familiar with github that's why i opened issue instead of question. 
so how can i share internet with the VM, plus i want to get the attached public ip when calling $ curl 'https://api.ipify.org?format=json' for example, is that possible ? thank you

**Comment by dealfonso** [comment]
No, you can't use such services, because the IP does not belong to the VM. You'll get the IP address from your NAT service.
